name: Test Package Quality

on: push

permissions:
  contents: read

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
    - name: Install package
      run: |
        python -m pip install -e .
    - name: Run Linting
      run: |
        pre-commit install
        pre-commit autoupdate
        pre-commit run --all
    - name: Unit tests
      run: |
        python -m pytest tests/
        rm -rf tmp/
